### ISSUE TITLE
Request To Add Files Downloading With Url

### ISSUE THREAD

**Issue by IbrahimKhan2004** [The-Hunter-Oraganization/Erika-Amano#18]
Hello Sir Can You Add Aria2c Or Aiohttp to Download Files With Url If Like Direct TG Files Takes More Times Like For 1Gb Files To Get Download It Take 3 Min Can You add It Please Downloading With Url It Will Be Good We Can Use FilestreamBot Or Mirror files And Can use Link To Download it On Bot And The Encode It 😊
Thank You....
Ibrahim

**Comment by soheru** [comment]
Hello Ibrahim,

Thank you for reaching out and sharing your suggestion. We appreciate your feedback and the feature you've proposed. Adding support for Aria2c or aiohttp to download files with URLs is indeed a valuable addition.

I understand that downloading large files, such as 1GB files, can take some time, and having the option to utilize FilestreamBot or mirror files would be beneficial. The ability to download files directly from a given URL and then encode them would be a useful feature for many users.

I'm glad to inform you that we have taken note of your request, and we will definitely consider adding this option in the next update. We strive to improve our services and provide a better experience for our users, so your input is highly valuable.

Thank you for your patience and understanding. If you have any further suggestions or questions, please feel free to let us know. We're here to assist you.

Best regards,
Soheru
