### ISSUE TITLE
4Gb Files Support 

### ISSUE THREAD

**Issue by IbrahimKhan2004** [The-Hunter-Oraganization/Erika-Amano#19]
Hello Sir I'm Here Again I'm Here With New Request Sir Please Add Compress Support Of 2Gb+ Files So Bot Can Compress Files Which Are Larger Then 2Gb It Will Be Very Helpful For Us 😊❤️
Thank You...

**Comment by soheru** [comment]
Hello again,

Thank you for coming back with another request. We appreciate your continued engagement and the feature you've suggested. Adding support for compressing files larger than 2GB would indeed be a valuable addition to the bot's functionality.

To implement this feature, we will need to update the source code to the latest Pyrogram version and make significant changes to the repository. While I don't have an exact timeframe for when these updates will be completed, please be assured that I have taken note of your request.

We understand the importance of providing efficient file compression capabilities, especially for larger files. Your feedback helps us prioritize our development efforts and deliver a better user experience.

Thank you for your patience and understanding. If you have any further suggestions or questions, please don't hesitate to reach out. We're here to assist you.

Best regards,
Soheru
